---
- hosts: jenkins
  become: true
  vars:
    jenkins_hostname: jenkins.lab.local    
    jenkins_plugins_state: present
    jenkins_plugins_install_dependencies: true
    jenkins_package_state: present        
    jenkins_plugins:
    - build-pipeline-plugin
    - ssh
    - ssh-slaves
    - git
    - github
    - log-parser
    - copyartifact
    - workflow-aggregator
    - workflow-multibranch
    - docker-workflow
    - template-project
  roles:
    - geerlingguy.jenkins