---
- hosts: jenkins
  become: true
  vars:
    jenkins_package_state: latest
    jenkins_hostname: jenkins.lab.local
  roles:
    - disable-selinux
    - add-hosts
    - firewall-8080
    - git
    - geerlingguy.java
    - geerlingguy.jenkins