---
- hosts: jenkins
  become: true
  vars:
    jenkins_hostname: jenkins.lab.local
    jenkins_plugins_install_dependencies: yes
    jenkins_plugins_state: present
    jenkins_plugins:
      - workflow-multibranch
      - git
  roles:
    - disable-selinux
    - add-hosts
    - firewall-8080
    - git
    - geerlingguy.jenkins